title: Incidia How To
description: The most common how to for things that are always asked
theme: just-the-docs

url: https://incidia-open-source.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: dark

callouts:
  info:
    title: Information
    color: blue
  warning:
    title: Warning
    color: red